steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        '$TRIGGER_NAME', 
        '--image', 
        'gcr.io/$PROJECT_ID/$TRIGGER_NAME', 
        '--region',
        'asia-east1',
        '--platform', 
        'managed', 
        '--quiet']
images:
  - gcr.io/$PROJECT_ID/$TRIGGER_NAME
<<<<<<< HEAD
timeout: 1200s
=======
timeout: 1200s
>>>>>>> 05ccf85e70375123904ad510d716034e06191602
